### ISSUE TITLE
Missing README.md for v0.1.0

### ISSUE THREAD

**Issue by TommasoRovelli** [angela-bonato/RayTracingCourse#5]
The README.md of v0.1.0 does not tell how to use that version.

**Comment by angela-bonato** [comment]
When the README.md file will be ready, we will release a new version. The new release will be v0.1.1 (as if the missing README.md represents a bug) or v0.2.0? We have to think about this...

Also, I am not entirely sure about the 'Usage' section of README.md, I think it is best to revise it before releasing it.

**Comment by angela-bonato** [comment]
It will be v0.1.1

**Comment by angela-bonato** [comment]
We released the 0.1.1 version from the Readme-v0.1.0 branch without merging it with the master branch.
